name: Update Quotes

on:
  schedule:
    - cron: "0 0 * * 5" # Runs every Friday  at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch: # Allows manually trigger

jobs:
  update-quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install axios puppeteer

      - name: Run script
        run: node backend/dataload.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add backend/quotes.json
          git commit -m 'Update quotes'
          git push
